# Generated by Django 3.2.5 on 2021-08-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyAverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('avg_value', models.FloatField(null=True, verbose_name='Average value')),
            ],
            options={
                'verbose_name': 'currency average',
                'verbose_name_plural': 'currencies averages',
                'ordering': ('id',),
            },
        ),
    ]
