# Generated by Django 3.2.5 on 2021-07-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create')),
                ('update', models.DateTimeField(auto_now=True, null=True, verbose_name='Update')),
                ('location', models.CharField(max_length=20, verbose_name='location')),
                ('loc_time', models.DateTimeField(verbose_name='location time')),
                ('temperature', models.FloatField(verbose_name='temperature')),
                ('weather_icons', models.CharField(max_length=254, verbose_name='weather icons')),
            ],
            options={
                'verbose_name': 'weather',
                'verbose_name_plural': 'weathers',
                'ordering': ('location',),
            },
        ),
    ]
