# Generated by Django 3.2.5 on 2021-07-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='basemodel_ptr',
        ),
        migrations.AddField(
            model_name='weather',
            name='create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create'),
        ),
        migrations.AddField(
            model_name='weather',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Update'),
        ),
        migrations.DeleteModel(
            name='BaseModel',
        ),
    ]
